export const LOCATION_SET = "LOCATION_SET";
export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR";
export const ADD_NEW_USER_DATA = "ADD_NEW_USER_DATA";
export const SET_STORED_DATA = "SET_STORED_DATA";
export const CHECK_USER_DATA = "CHECK_USER_DATA";
